<?php

$data = [
	'id' => $itempo['id'],
	'nopo' => $itempo['nopo'],
	'nopotxt' => $itempo['nopotxt'],
	'noppo' => $itempo['noppo'],
	'noppotxt' => $itempo['noppotxt'],
	'refppo' => $itempo['refppo'],
	'tglppo' => $itempo['tglppo'],
	'tglppotxt' => $itempo['tglppotxt'],
	'tglpo' => $itempo['tglpo'],
	'tglpotxt' => $itempo['tglpotxt'],

	'kodebar' => $itempo['kodebar'],
	'kodebartxt' => $itempo['kodebartxt'],
	'nabar' => $itempo['nabar'],
	'sat' => $itempo['sat'],
	'qty' => $itempo['qty'],
	'harga' => $itempo['harga'],
	'jumharga' => $itempo['jumharga'],
	'kodept' => $itempo['kodept'],
	'namapt' => $itempo['namapt'],
	'periode' => $itempo['periode'],

	'periodetxt' => $itempo['periodetxt'],
	'thn' => $itempo['thn'],
	'merek' => $itempo['merek'],
	'tglisi' => $itempo['tglisi'],
	'user' => $itempo['user'],
	'ket' => $itempo['ket'],
	'noref' => $itempo['noref'],
	'lokasi' => $itempo['lokasi'],
	'hargasblm' => $itempo['hargasblm'],
	'disc' => $itempo['disc'],

	'kurs' => $itempo['kurs'],
	'kode_budget' => $itempo['kode_budget'],
	'grup' => $itempo['grup'],
	'main_acct' => $itempo['main_acct'],
	'nama_main' => $itempo['nama_main'],
	'batal' => $itempo['batal'],
	'cek_pp' => $itempo['cek_pp'],
	'KODE_BPO' => $itempo['KODE_BPO'],
	'JUMLAHBPO' => $itempo['JUMLAHBPO'],
	'kode_bebanbpo' => $itempo['kode_bebanbpo'],

	'nama_bebanbpo' => $itempo['nama_bebanbpo'],
	'konversi' => $itempo['konversi'],
];
